function A = przyklad5(N)
% Jakaś taka macierz pięcioprzekątniowa

A = 4 * eye(N) + ...
    diag(-2 * ones(N-1,1),  1) + ...
    diag(-2 * ones(N-1,1), -1) + ...
    diag(ones(N-2,1), 2) + ...
    diag(ones(N-2,1), -2);

end


